#!/bin/bash

COLOR_GREEN='\e[32m'
COLOR_RESET='\e[0m'

Database="database"

if [ -d "$Database" ]; then
    cd ./"$Database"
    echo "Connected"
else
    mkdir ./"$Database"
    cd ./"$Database"
    echo "Connected"
fi

while true; do

    select features in "Create DB" "List DB's" "Drop DB" "Connect to DB" "Quit"; do

        case $REPLY in
        1)
            while true; do

                read -p "Please enter DB name: " DB_name

                if [[ ! "$DB_name" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; then
                    echo "DB name shall only include letters and underscores, and no spaces allowed. Please try again."
                elif [ -e "$DB_name" ]; then
                    echo "DB already exists. Please choose a different name."
                else
                    mkdir ./"$DB_name"
                    echo "$DB_name database created successfully"
                    break
                fi
            done
            ;;

        2)
            counter1=1
            echo -e "${COLOR_GREEN}List of Databases:${COLOR_RESET}"
            for dir in */; do
                echo -e " ${COLOR_GREEN}$counter1.${dir%/}${COLOR_RESET}"
                ((counter1++))
            done
            ;;

        3)
            while true; do
                read -p "Please enter DB name to drop: " DB_name

                if [ -d "$DB_name" ]; then
                    rm -r ./"$DB_name"
                    echo "$DB_name database is dropped successfully"
                    break
                else
                    echo "Database does not exist. Please try again."
                fi
            done
            ;;

        4)
            while true; do
                read -p "Please enter DB name to connect: " DB_name

                if [[ ! ( "$DB_name" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ) || ! ( -e "$DB_name" ) ]]; then
                    echo "Database does not exist or invalid name. Please try again."
                else
                    cd ./"$DB_name"
                    echo "You are connected to $DB_name database"
                    break
                fi
            done

            while true; do
                select operation in "Select" "Insert" "Update" "Delete" "Create table" "Drop table" "list tables" "Back to menu"; do
                    case $REPLY in
                    1)
                        source ../../select
                        ;;
                    2)
                        source ../../insert
                        ;;
                    3)
			source ../../Update
                        ;;
		    4)
			source ../../delete
			;;		
	
		    5)
			source ../../create_table
			;;
		    6)
			source ../../drop_table
			;;

		    7)
			ls -1 ./ | grep -v '_metadata$' | awk '{print NR, $0}'

			;;
		    8)
			cd ..
                        break
			;; 			
                    *)
                        echo "Please choose an option from the list"
                        ;;
                    esac
                done
		break
            done
            ;;

        5)
            echo "Database engine is disconnecting..."
            sleep 2
            echo "Disconnected"
            break
            ;;

        *)
            echo "Please Choose an option from the list"
            ;;
        esac
    done
    break
done

