#!/bin/bash
echo -e "List of Tables:"
counter=1
valid_values=()

# Display a list of tables
for file in *; do
    if [ -f "$file" ] && [[ ! "$file" =~ _metadata$ ]]; then
        echo -e "${COLOR_GREEN} $counter. $file ${COLOR_RESET}"
        ((counter++))
    fi
done
			
    			
			while true; do
				# Take the table name from the user
				read -p "Enter the name of a table you want to delete: " table
				if [[ -f "$table" ]]; then

				# Remove/delete the table
				rm "$table"

				# Check if the table is deleted or not
				if [ $? -eq 0 ]; then
					echo -e "Table successfully deleted.\n"
					rm  "${table}_metadata"
					break
				else
					echo -e "Failed to delete the table\nPlease make sure of the table name.\n"
				fi
			 else
			echo "Table not exist"
			continue
			fi 
			done
